apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitness-app-sa
  namespace: default
  annotations:
    # This Client ID tells Workload Identity which Azure Identity to assume
    # Replace the value below with the Client ID(managed identity)
    azure.workload.identity/client-id: "d15ca06b-c7b6-4429-b31e-edfbb7788ad8"
  labels:
    azure.workload.identity/use: "true"
