apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitness-app-sa
  namespace: default
  annotations:
    # This Client ID tells Workload Identity which Azure Identity to assume
    # Replace the value below with the Client ID(managed identity)
    azure.workload.identity/client-id: "f925bd55-68a2-4c3e-a48a-e593cccd3765"
  labels:
    azure.workload.identity/use: "true"
