apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-fitness-app
  namespace: default
spec:
  provider: azure
  secretObjects:
  # This section creates a regular Kubernetes Secret from the Key Vault data
  # so that the Pod can load it into environment variables easily.
  - secretName: fitness-app-env-secret
    type: Opaque
    data:
    # 'objectName' must match the secret name in Key Vault
    # 'key' will be the name of the environment variable in Kubernetes
    - objectName: CosmosDb
      key: MONGODB_URI
    - objectName: JwtSecret
      key: JWT_SECRET
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "f925bd55-68a2-4c3e-a48a-e593cccd3765" # Replace with your Client ID
    keyvaultName: "Fit-kv1" # Replace with your Key Vault name
    tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394" # You can get this by running: az account show --query tenantId -otsv
    objects: |
      array:
        - |
          objectName: CosmosDb
          objectType: secret
          objectVersion: ""
        - |
          objectName: JwtSecret
          objectType: secret
          objectVersion: ""
